#!/usr/bin/env zsh

echo "Installing Homebrew, a good OS X package manager ..."
  /usr/bin/ruby -e "$(/usr/bin/curl -fksSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)"
  brew update

echo "Put Homebrew location earlier in PATH ..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.zshrc
  source ~/.zshrc

echo "Installing ack, a good way to search through files ..."
  brew install ack

echo "Installing ImageMagick, good for cropping and re-sizing images ..."
  brew install imagemagick

echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
  brew install qt

echo "Installing RVM (Ruby Version Manager) ..."
  bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshrc
  source ~/.zshrc

zsh < <(curl -s https://raw.github.com/thoughtbot/laptop/master/ruby)
